// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'ar'
	| 'ckb'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​i​ ​{​n​a​m​e​}​!​ ​P​l​e​a​s​e​ ​l​e​a​v​e​ ​a​ ​s​t​a​r​ ​i​f​ ​y​o​u​ ​l​i​k​e​ ​t​h​i​s​ ​p​r​o​j​e​c​t​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​i​v​a​n​h​o​f​e​r​/​t​y​p​e​s​a​f​e​-​i​1​8​n
	 * @param {string} name
	 */
	HI: RequiredParams<'name'>
	/**
	 * H​o​m​e
	 */
	home: string
	/**
	 * A​b​o​u​t
	 */
	about: string
	/**
	 * C​o​n​t​a​c​t
	 */
	contact: string
	/**
	 * N​e​w​s
	 */
	news: string
	/**
	 * S​e​r​v​i​c​e​s
	 */
	services: string
	/**
	 * E​x​h​i​b​i​t​i​o​n
	 */
	exhibition: string
}

export type TranslationFunctions = {
	/**
	 * Hi {name}! Please leave a star if you like this project: https://github.com/ivanhofer/typesafe-i18n
	 */
	HI: (arg: { name: string }) => LocalizedString
	/**
	 * Home
	 */
	home: () => LocalizedString
	/**
	 * About
	 */
	about: () => LocalizedString
	/**
	 * Contact
	 */
	contact: () => LocalizedString
	/**
	 * News
	 */
	news: () => LocalizedString
	/**
	 * Services
	 */
	services: () => LocalizedString
	/**
	 * Exhibition
	 */
	exhibition: () => LocalizedString
}

export type Formatters = {}
